spring.application.name=user

spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=myuser
spring.datasource.password=secret

server.port=8083
spring.jpa.hibernate.ddl-auto=update

spring.cloud.stream.default-binder=kafka
spring.cloud.stream.kafka.binder.brokers=localhost:9092

spring.cloud.stream.bindings.kafka-user-event.destination=user.events.topic
spring.cloud.stream.bindings.kafka-user-event.content-type=application/json

spring.cloud.stream.bindings.kafka-user-checkout-out-0.destination=user.checkout.topic
spring.cloud.stream.bindings.kafka-user-checkout-out-0.content-type=application/json

spring.cloud.function.definition=orderPlacedIn;orderCompletedIn;orderFailedIn;productCreatedIn;productChangedPriceIn

spring.cloud.stream.bindings.orderPlacedIn-in-0.destination=order.events.topic
spring.cloud.stream.bindings.orderPlacedIn-in-0.group=user-order-placed-group

spring.cloud.stream.bindings.orderCompletedIn-in-0.destination=order.events.topic
spring.cloud.stream.bindings.orderCompletedIn-in-0.group=user-order-completed-group

spring.cloud.stream.bindings.orderFailedIn-in-0.destination=order.events.topic
spring.cloud.stream.bindings.orderFailedIn-in-0.group=user-order-failed-group

spring.cloud.stream.bindings.productCreatedIn-in-0.destination=product.events.topic
spring.cloud.stream.bindings.productCreatedIn-in-0.group=user-product-created-group

spring.cloud.stream.bindings.productChangedPriceIn-in-0.destination=product.events.topic
spring.cloud.stream.bindings.productChangedPriceIn-in-0.group=user-product-price-group