{
 "title": "Product",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROM", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Price",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "product_price", "legendFormat": "{{product_name}}" }
   ]
  },
  {
   "title": "Stock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "product_stock", "legendFormat": "{{product_name}}" }
   ]
  },
  {
   "title": "Created",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "product_create_total", "legendFormat": "__auto" }
   ]
  }
 ]
}