{
 "title": "User",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROM", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Registered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "user_register_total", "legendFormat": "Registered" }
   ]
  },
  {
   "title": "Completed Orders",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "user_cart_complete_total", "legendFormat": "{{user_name}}" }
   ]
  },
  {
   "title": "Cart Items",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "user_cart_add_total", "legendFormat": "{{user_name}}" }
   ]
  },
  {
   "title": "User Cart Checkout",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "user_cart_checkout_total", "legendFormat": "{{user_name}}" }
   ]
  }
 ]
}