spring.application.name=order

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/order_db
spring.datasource.username=myuser
spring.datasource.password=secret

server.port=8081
spring.jpa.hibernate.ddl-auto=update

spring.cloud.stream.default-binder=kafka
spring.cloud.stream.kafka.binder.brokers=${KAFKA_SERVER_URL:localhost:9092}

spring.cloud.stream.bindings.kafka-order-event.destination=order.events.topic
spring.cloud.stream.bindings.kafka-order-event.content-type=application/json

spring.cloud.function.definition=userEventsIn;productReducedStockIn;productFailedToReduceStockIn

spring.cloud.stream.bindings.userEventsIn-in-0.destination=user.checkout.topic
spring.cloud.stream.bindings.userEventsIn-in-0.group=order-user-group

spring.cloud.stream.bindings.productReducedStockIn-in-0.destination=product.reduced.topic
spring.cloud.stream.bindings.productReducedStockIn-in-0.group=order-reduced-group

spring.cloud.stream.bindings.productFailedToReduceStockIn-in-0.destination=product.failed.topic
spring.cloud.stream.bindings.productFailedToReduceStockIn-in-0.group=order-failed-group

eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER_URL:http://localhost:8167/eureka/}
eureka.instance.prefer-ip-address=true
