spring.application.name=user

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/user_db
spring.datasource.username=myuser
spring.datasource.password=secret

server.port=8083
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health,prometheus
management.metrics.tags.application=${spring.application.name}
management.endpoint.health.show-details=always

spring.cloud.stream.default-binder=kafka
spring.cloud.stream.kafka.binder.brokers=${KAFKA_SERVER_URL:localhost:9092}

spring.cloud.stream.bindings.kafka-user-event-out-0.destination=user.events.topic
spring.cloud.stream.bindings.kafka-user-event-out-0.content-type=application/json

spring.cloud.stream.bindings.kafka-user-checkout-out-0.destination=user.checkout.topic
spring.cloud.stream.bindings.kafka-user-checkout-out-0.content-type=application/json

spring.cloud.function.definition=orderPlacedIn

spring.cloud.stream.bindings.orderPlacedIn-in-0.destination=order.placed.topic
spring.cloud.stream.bindings.orderPlacedIn-in-0.group=user-order-group

eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER_URL:http://localhost:8167/eureka/}
eureka.instance.prefer-ip-address=true
