gradle := "./gradlew"
order := "./order/build/libs/order-0.0.1-SNAPSHOT.jar"
user := "./user/build/libs/user-0.0.1-SNAPSHOT.jar"
product := "./product/build/libs/product-0.0.1-SNAPSHOT.jar"
gateway := "./gateway/build/libs/gateway-0.0.1-SNAPSHOT.jar"
discovery := "./discovery/build/libs/discovery-0.0.1-SNAPSHOT.jar"

clean:
    {{ gradle }} clean

build:
    {{ gradle }} build

run:
    {{ gradle }} :discovery:bootRun & \
    sleep 10; \
    {{ gradle }} :user:bootRun & \
    {{ gradle }} :product:bootRun & \
    {{ gradle }} :order:bootRun & \
    {{ gradle }} :gateway:bootRun

bnr:
    {{ gradle }} build -x test
    {{ gradle }} :discovery:bootRun & \
    sleep 10; \
    {{ gradle }} :user:bootRun & \
    {{ gradle }} :product:bootRun & \
    {{ gradle }} :order:bootRun & \
    {{ gradle }} :gateway:bootRun

kill:
    -pkill -f 'java -jar' || true
