spring.application.name=product

spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=myuser
spring.datasource.password=secret

server.port=8082
spring.jpa.hibernate.ddl-auto=update

spring.cloud.stream.default-binder=kafka
spring.cloud.stream.kafka.binder.brokers=localhost:9092

spring.cloud.function.definition=orderPlacedIn

spring.cloud.stream.bindings.orderPlacedIn-in-0.destination=order.events.topic
spring.cloud.stream.bindings.orderPlacedIn-in-0.group=product-order-group

spring.cloud.stream.bindings.kafka-product-event.destination=product.events.topic
spring.cloud.stream.bindings.kafka-product-event.content-type=application/json

spring.cloud.stream.bindings.kafka-product-reduced-out-0.destination=product.reduced.topic
spring.cloud.stream.bindings.kafka-product-reduced-out-0.content-type=application/json

spring.cloud.stream.bindings.kafka-product-failed-out-0.destination=product.failed.topic
spring.cloud.stream.bindings.kafka-product-failed-out-0.content-type=application/json