services:
  product-db:
    image: postgres:16-alpine
    container_name: "product-db"
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  order-db:
    image: postgres:16-alpine
    container_name: "order-db"
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  user-db:
    image: postgres:16-alpine
    container_name: "user-db"
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  # --- Microservices ---
  product-service:
    image: eclipse-temurin:21-jre-alpine
    container_name: product-service
    ports: ["8081:8081"]
    volumes: ["./service/product/build/libs/product.jar:/app/service.jar"]
    command: ["java", "-jar", "/app/service.jar"]
    init: true
    depends_on: [product-db]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/product_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092

  order-service:
    image: eclipse-temurin:21-jre-alpine
    container_name: order-service
    ports: ["8082:8082"]
    volumes: ["./service/order/build/libs/order.jar:/app/service.jar"]
    command: ["java", "-jar", "/app/service.jar"]
    init: true
    depends_on: [order-db]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/order_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092

  user-service:
    image: eclipse-temurin:21-jre-alpine
    container_name: user-service
    ports: ["8083:8083"]
    volumes: ["./service/user/build/libs/user.jar:/app/service.jar"]
    command: ["java", "-jar", "/app/service.jar"]
    init: true
    depends_on: [user-db]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092

  api-gateway:
    image: eclipse-temurin:21-jre-alpine
    container_name: api-gateway
    ports: ["8080:8080"]
    volumes: ["./app/build/libs/app.jar:/app/service.jar"]
    command: ["java", "-jar", "/app/service.jar"]
    init: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
