spring.application.name=user

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/user_db
spring.datasource.username=myuser
spring.datasource.password=secret

server.port=8083
spring.jpa.hibernate.ddl-auto=update

spring.cloud.stream.default-binder=kafka
spring.cloud.stream.kafka.binder.brokers=${KAFKA_SERVER_URL:localhost:9092}

spring.cloud.stream.bindings.kafka-user-event.destination=user.events.topic
spring.cloud.stream.bindings.kafka-user-event.content-type=application/json

spring.cloud.stream.bindings.kafka-user-checkout-out-0.destination=user.checkout.topic
spring.cloud.stream.bindings.kafka-user-checkout-out-0.content-type=application/json

spring.cloud.function.definition=orderPlacedIn

eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER_URL:http://localhost:8167/eureka/}
eureka.instance.prefer-ip-address=true
